name: Phoenix Test Automation Workflow


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule: # Set the CRON for MIDNIGHT IST ---- UTC
    - cron: "30 18  *"        
    //remove timer
  

  workflow_dispatch: 
     inputs:
         env:
           description: "Environment"
           type: choice
           options: [qa,uat,dev]
           default: qa
           required: true
           
         suiteXmlFile:
           description: "Testng xml file"
           type: choice
           options: [testng.xml,smoke.xml,regression.xml]
           default: testng.xml
           required: true
   
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Default value for execution
      id : default
      run: |
            echo "suiteXmlFile="${{ github.event.inputs.suiteXMLFile || 'testng.xml' }}" >> $github_Output 
            echo "env=-"${{ github.event.inputs.env || 'qa' }}" >>  $github_Output 
     
    - name: Execute Test Automation Framework
      run: mvn clean test -DsuiteXmlFile="${{ steps.default.outputs.suiteXMLFile }}" -Denv="${{ steps.default.outputs.env }}"

 
    - name: upload build artifact
      if: always()
      uses: actions/upload-artifact@v5.0.0
      with:
          name: surefire report
          path: target/surefire-reports/
          retention-days: 10
      
      
      
